### ISSUE TITLE
Name Collision w/Python-Ldap

### ISSUE THREAD

**Issue by danieldjewell** [abilian/ldif#4]
Unfortunately, this package has a name collision with the `python-ldap` package ... 

Both use the `ldif` namespace, which creates problems - as in you can't install both.

**Comment by sfermigier** [comment]
As stated in the README's introduction: "This is a fork of the ldif module from [python-ldap](http://www.python-ldap.org/) with python3/unicode support."

So this is expected.

You shouldn't be using both at the same time.
