### ISSUE TITLE
ldapmodify generation is not working

### ISSUE THREAD

**Issue by nhamilakis** [abilian/ldif#5]
I am trying to generate an LDIF file to run through the ldapmodify command, but it's not working.
Here is the relevant code :

```python 
ldif_writer = LDIFWriter(file.open('wb'))
ldif_writer.unparse(
    dn=dn, record=dict(
        changetype=["modify"],
        add=['memberUid'],
        memberUid=[username]
    )) 
```
The result file created looks like this : 

```
dn: cn=group-name,dc=company,dc=com
add: memberUid
changetype: modify
memberUid: user1
```

Which when used with the `ldapmodify` command raises the following error : 

```
ldapmodify: wrong attributeType at line 3, entry "cn=group-name,dc=company,dc=com"
```

I manually edited the ldif file and inverted the changetype line as it needs to be before the add line
as follows 

```
dn: cn=group-name,dc=company,dc=com
changetype: modify
add: memberUid
memberUid: user1
```

And the command works fine. Is there another way to generate modify files that i missed ? Maybe there should be a way to force the order of attributes (list, OrderedDict)

Thanks in advance for your help, this module is very useful, as i could find no other that allowed to just parse LDIF files without having the rest of the LDAP functionalities.

**Comment by ch-IAE-HSN** [comment]
+1 for me!

I removed the sorted-Function in line 138, et voila, the keys appear in the generated ldif in the order they were entered...

**Comment by Wenkow** [comment]
I am struggling with sorted entries. Removed sorted function causes unwanted reordering and in some cases "changetype" entry is not the first entry in final ldiff object (right after dn). This should be imho done always, no matter how the rest of entries is un/sorted.

Release 4.2.5 is causing unpredictable troubles based on mix of an attributes used.
